datasets:
  ende:
    source:
      _target_: src.dataprep.processing.ReadSource
      directory : ${data_root}/ende # ${encoders_root}/${directory}/* is where files should be
      langs : [en, de]
      cache_dir: ${data_root}/cache
    flow:
      transform_order: [bad_line_filter, ]  #bad_token_remove, bad_length_filter, bad_accent_replace]
      bad_line_filter:
        _target_: src.dataprep.processing.CleanText
        op: bad_line_filter
        tags: ['<url>', '<keyword>', '<talkid>']
      bad_token_remove:
        _target_: src.dataprep.processing.CleanText
        op: bad_token_remove
        tags: ['</title>', '<title>', '<description>', '</description>']
      bad_length_remove:
        _target_: src.dataprep.processing.CleanText
        op: bad_length_remove
      bad_accent_replace:
        _target_: src.dataprep.processing.CleanText
        op: bad_accent_replace
    process_flow:
      _target_: src.dataprep.processing.ProcessFlow